### ISSUE TITLE
a few things to tinker

### ISSUE THREAD

**Issue by ShirMon** [AhronCohen/Bidud#2]
- Filter wrong input; chars, pid that doesn't exist, no argument at all. (return a how-to-use output)
- Format not user-friendly, try to format it like so:
          ++grandparent
          +parent
          givenPID
          -child
          -child
          --grandchild
- Do not use a file in the script (ParentList)
- To make it look cleaner declare the functions before the beginning if statement and not inside the if statement
- The given PID is printed twice, once just as a number and a second time as "pid number X"

Other than that well done! Took me a lot longer to complete this task!

**Comment by AhronCohen** [comment]
thanks.
i will work on it now.
