### ISSUE TITLE
small fixes

### ISSUE THREAD

**Issue by ShirMon** [AhronCohen/Bidud#8]
![image](https://user-images.githubusercontent.com/59015114/80071129-c3f76300-854c-11ea-96ba-a8690919be3e.png)
It's not working :(
And you used echo instead of EOF for the fdisk input? could you please change it to EOF?

_Originally posted by @ShirMon in https://github.com/AhronCohen/Bidud/pull/7#issuecomment-618230531_

**Comment by AhronCohen** [comment]
its not empty, there is a fileSystem in this place..
i can do it with EOF but its not looking so nice, it will look like this:
fdisk -c /dev/$1 &> /dev/null << EOF
n
e



n



w
EOF

**Comment by ShirMon** [comment]
Ok, you don't have to use EOF as long as you know how to use it! :)

your code takes into consideration the lost+find folder.

**Comment by AhronCohen** [comment]
oops there is problem with the "wc -l "fix i forgot to put the path...
but if there is lost+found i dont want to create filesystem in there..because its allready filesystem no?

**Comment by AhronCohen** [comment]
Ok i solved it.
